# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ListItem_UI(object):
    def setupUi(self, sender, msg, time):
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sender = QtWidgets.QLabel(self)
        self.sender.setStyleSheet("padding-left:10px; min-width:224px;")
        self.sender.setObjectName("sender")
        self.horizontalLayout.addWidget(self.sender)
        self.time = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time.sizePolicy().hasHeightForWidth())
        self.time.setSizePolicy(sizePolicy)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.horizontalLayout.addWidget(self.time)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.MsgLabel = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgLabel.sizePolicy().hasHeightForWidth())
        self.MsgLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time.setStyleSheet("min-width:192px;")
        self.MsgLabel.setFont(font)
        self.MsgLabel.setStyleSheet("margin:7px;\n"
                                    "border-radius: 10px;\n"
                                    "background:#DEDEDE;\n"
                                    "padding:5px;\n"
                                    "margin-left:15px;")
        self.MsgLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.MsgLabel.setWordWrap(True)
        self.MsgLabel.setObjectName("MsgLabel")
        self.verticalLayout.addWidget(self.MsgLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(1, 50)
        self.sender.setText(sender)
        self.time.setText(time)
        self.MsgLabel.setText(msg)
